<?php

namespace Database\Seeders;

use App\Models\Achievement;
use App\Models\Game;
use Illuminate\Database\Seeder;
use Str;

class DemoGameAchievementsSeeder extends Seeder
{
    public function run()
    {
        /** @var Game $game */
        foreach (Game::cursor() as $game) {
            $achivements = $this->achivements()
                ->get($game->id)
                ->map(fn($achievement) => new Achievement($achievement));
            $game->achievements()->saveMany($achivements);
        }
    }

    public function achivements()
    {
        return collect([
            '753501ba-a9fa-437b-8b44-8d8ca42f18ab' => collect([
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'One by one',
                    'description' => 'Eat 10 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Get eating',
                    'description' => 'Eat your first player',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Predator',
                    'description' => 'Eat 50 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Short lived',
                    'description' => 'Survive 1 minute',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Cell survivor',
                    'description' => 'Survive 30 minutes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Took ten',
                    'description' => 'Survive 10 minutes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Rookie',
                    'description' => 'Reach Level 5',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Veteran',
                    'description' => 'Reach Level 20',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Release the Kraken',
                    'description' => 'Reach Level 100',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Master',
                    'description' => 'Reach Level 50',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Sliding along',
                    'description' => 'Reach top 30 in classic mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Among the best',
                    'description' => 'Reach top 10 in classic mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'In a Rush',
                    'description' => 'Finish a Rush match',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eye on the prize',
                    'description' => 'Finish top 10 in Rush mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Mother Cell',
                    'description' => 'Finish top 1 in Rush mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'One by one',
                    'description' => 'Eat 10 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '50 Points',
                    'description' => 'Unlocks after you have obtained 50 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '60 Points',
                    'description' => 'Unlocks after you have obtained 60 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '70 Points',
                    'description' => 'Unlocks after you have obtained 70 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '80 Points',
                    'description' => 'Unlocks after you have obtained 80 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '90 Points',
                    'description' => 'Unlocks after you have obtained 90 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '100 Points',
                    'description' => 'Unlocks after you have obtained 100 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '110 Points',
                    'description' => 'Unlocks after you have obtained 110 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '120 Points',
                    'description' => 'Unlocks after you have obtained 120 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '130 Points',
                    'description' => 'Unlocks after you have obtained 130 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '140 Points',
                    'description' => 'Unlocks after you have obtained 140 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '150 Points',
                    'description' => 'Unlocks after you have obtained 150 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '160 Points',
                    'description' => 'Unlocks after you have obtained 160 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '170 Points',
                    'description' => 'Unlocks after you have obtained 170 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '180 Points',
                    'description' => 'Unlocks after you have obtained 180 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '190 Points',
                    'description' => 'Unlocks after you have obtained 190 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '200 Points',
                    'description' => 'Unlocks after you have obtained 200 points in a single game.',
                ],
                // Extras
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Murder Snake',
                    'description' => 'Kill an other snake.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Homicidal Viper',
                    'description' => 'Kill 25 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Killer Python',
                    'description' => 'Kill 100 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Slayer of Constrictors',
                    'description' => 'Kill 500 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Murderous Anaconda',
                    'description' => 'Kill 1k other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Underground Mamba',
                    'description' => 'Kill 5k other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Getting Snaky',
                    'description' => 'Reach a length of 1k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Lengthy Reptile',
                    'description' => 'Reach a length of 10k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Elongated Cobra',
                    'description' => 'Reach a length of 100k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Infinite Invertebrate',
                    'description' => 'Reach a length of 1m',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Hungry Snakelet',
                    'description' => 'Eat 1k pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Gluttonous Adder',
                    'description' => 'Eat 50k pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Voracious Habu',
                    'description' => 'Eat 1m pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Play 7 consecutive days.',
                    'description' => 'Play 7 consecutive days.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 75 buildings in classic or battle mode.',
                    'description' => 'Eat 75 buildings in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 50 cars in classic or battle mode.',
                    'description' => 'Eat 50 cars in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 100 people in classic or battle mode.',
                    'description' => 'Eat 100 people in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 15 cops in classic or battle mode.',
                    'description' => 'Eat 15 cops in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'End a game at first place in classic mode.',
                    'description' => 'End a game at first place in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Score 1000 points in classic mode.',
                    'description' => 'Score 1000 points in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Score 2000 points in classic mode.',
                    'description' => 'Score 2000 points in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Kill 10 holes in classic mode.',
                    'description' => 'Kill 10 holes in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the max size 3 times in classic mode.',
                    'description' => 'Reach the max size 3 times in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the silver rank.',
                    'description' => 'Reach the silver rank.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the gold rank.',
                    'description' => 'Reach the gold rank.',
                ],
            ])->merge(
                Achievement::factory()
                    ->count(300)
                    ->make()
                    ->toArray(),
            ),
            '2934ceee-e195-4cd0-ae6a-d2098c810917' => collect([
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Murder Snake',
                    'description' => 'Kill an other snake.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Homicidal Viper',
                    'description' => 'Kill 25 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Killer Python',
                    'description' => 'Kill 100 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Slayer of Constrictors',
                    'description' => 'Kill 500 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Murderous Anaconda',
                    'description' => 'Kill 1k other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Underground Mamba',
                    'description' => 'Kill 5k other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Getting Snaky',
                    'description' => 'Reach a length of 1k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Lengthy Reptile',
                    'description' => 'Reach a length of 10k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Elongated Cobra',
                    'description' => 'Reach a length of 100k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Infinite Invertebrate',
                    'description' => 'Reach a length of 1m',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Hungry Snakelet',
                    'description' => 'Eat 1k pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Gluttonous Adder',
                    'description' => 'Eat 50k pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Voracious Habu',
                    'description' => 'Eat 1m pellets',
                ],
                // extras
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'One by one',
                    'description' => 'Eat 10 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Get eating',
                    'description' => 'Eat your first player',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Predator',
                    'description' => 'Eat 50 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Short lived',
                    'description' => 'Survive 1 minute',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Cell survivor',
                    'description' => 'Survive 30 minutes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Took ten',
                    'description' => 'Survive 10 minutes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Rookie',
                    'description' => 'Reach Level 5',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Veteran',
                    'description' => 'Reach Level 20',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Release the Kraken',
                    'description' => 'Reach Level 100',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Master',
                    'description' => 'Reach Level 50',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Sliding along',
                    'description' => 'Reach top 30 in classic mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Among the best',
                    'description' => 'Reach top 10 in classic mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'In a Rush',
                    'description' => 'Finish a Rush match',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eye on the prize',
                    'description' => 'Finish top 10 in Rush mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Mother Cell',
                    'description' => 'Finish top 1 in Rush mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'One by one',
                    'description' => 'Eat 10 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '50 Points',
                    'description' => 'Unlocks after you have obtained 50 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '60 Points',
                    'description' => 'Unlocks after you have obtained 60 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '70 Points',
                    'description' => 'Unlocks after you have obtained 70 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '80 Points',
                    'description' => 'Unlocks after you have obtained 80 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '90 Points',
                    'description' => 'Unlocks after you have obtained 90 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '100 Points',
                    'description' => 'Unlocks after you have obtained 100 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '110 Points',
                    'description' => 'Unlocks after you have obtained 110 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '120 Points',
                    'description' => 'Unlocks after you have obtained 120 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '130 Points',
                    'description' => 'Unlocks after you have obtained 130 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '140 Points',
                    'description' => 'Unlocks after you have obtained 140 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '150 Points',
                    'description' => 'Unlocks after you have obtained 150 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '160 Points',
                    'description' => 'Unlocks after you have obtained 160 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '170 Points',
                    'description' => 'Unlocks after you have obtained 170 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '180 Points',
                    'description' => 'Unlocks after you have obtained 180 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '190 Points',
                    'description' => 'Unlocks after you have obtained 190 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '200 Points',
                    'description' => 'Unlocks after you have obtained 200 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Play 7 consecutive days.',
                    'description' => 'Play 7 consecutive days.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 75 buildings in classic or battle mode.',
                    'description' => 'Eat 75 buildings in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 50 cars in classic or battle mode.',
                    'description' => 'Eat 50 cars in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 100 people in classic or battle mode.',
                    'description' => 'Eat 100 people in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 15 cops in classic or battle mode.',
                    'description' => 'Eat 15 cops in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'End a game at first place in classic mode.',
                    'description' => 'End a game at first place in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Score 1000 points in classic mode.',
                    'description' => 'Score 1000 points in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Score 2000 points in classic mode.',
                    'description' => 'Score 2000 points in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Kill 10 holes in classic mode.',
                    'description' => 'Kill 10 holes in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the max size 3 times in classic mode.',
                    'description' => 'Reach the max size 3 times in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the silver rank.',
                    'description' => 'Reach the silver rank.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the gold rank.',
                    'description' => 'Reach the gold rank.',
                ],
            ])->merge(
                Achievement::factory()
                    ->count(300)
                    ->make()
                    ->toArray(),
            ),
            '1db03dcf-f131-4a8d-bbe4-c8c8d2d5198b' => collect([
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Play 7 consecutive days.',
                    'description' => 'Play 7 consecutive days.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 75 buildings in classic or battle mode.',
                    'description' => 'Eat 75 buildings in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 50 cars in classic or battle mode.',
                    'description' => 'Eat 50 cars in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 100 people in classic or battle mode.',
                    'description' => 'Eat 100 people in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eat 15 cops in classic or battle mode.',
                    'description' => 'Eat 15 cops in classic or battle mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'End a game at first place in classic mode.',
                    'description' => 'End a game at first place in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Score 1000 points in classic mode.',
                    'description' => 'Score 1000 points in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Score 2000 points in classic mode.',
                    'description' => 'Score 2000 points in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Kill 10 holes in classic mode.',
                    'description' => 'Kill 10 holes in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the max size 3 times in classic mode.',
                    'description' => 'Reach the max size 3 times in classic mode.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the silver rank.',
                    'description' => 'Reach the silver rank.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Reach the gold rank.',
                    'description' => 'Reach the gold rank.',
                ],
                // extras
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'One by one',
                    'description' => 'Eat 10 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Get eating',
                    'description' => 'Eat your first player',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Predator',
                    'description' => 'Eat 50 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Short lived',
                    'description' => 'Survive 1 minute',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Cell survivor',
                    'description' => 'Survive 30 minutes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Took ten',
                    'description' => 'Survive 10 minutes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Rookie',
                    'description' => 'Reach Level 5',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Veteran',
                    'description' => 'Reach Level 20',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Release the Kraken',
                    'description' => 'Reach Level 100',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Master',
                    'description' => 'Reach Level 50',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Sliding along',
                    'description' => 'Reach top 30 in classic mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Among the best',
                    'description' => 'Reach top 10 in classic mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'In a Rush',
                    'description' => 'Finish a Rush match',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Eye on the prize',
                    'description' => 'Finish top 10 in Rush mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Mother Cell',
                    'description' => 'Finish top 1 in Rush mode',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'One by one',
                    'description' => 'Eat 10 players',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '50 Points',
                    'description' => 'Unlocks after you have obtained 50 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '60 Points',
                    'description' => 'Unlocks after you have obtained 60 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '70 Points',
                    'description' => 'Unlocks after you have obtained 70 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '80 Points',
                    'description' => 'Unlocks after you have obtained 80 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '90 Points',
                    'description' => 'Unlocks after you have obtained 90 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '100 Points',
                    'description' => 'Unlocks after you have obtained 100 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '110 Points',
                    'description' => 'Unlocks after you have obtained 110 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '120 Points',
                    'description' => 'Unlocks after you have obtained 120 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '130 Points',
                    'description' => 'Unlocks after you have obtained 130 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '140 Points',
                    'description' => 'Unlocks after you have obtained 140 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '150 Points',
                    'description' => 'Unlocks after you have obtained 150 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '160 Points',
                    'description' => 'Unlocks after you have obtained 160 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '170 Points',
                    'description' => 'Unlocks after you have obtained 170 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '180 Points',
                    'description' => 'Unlocks after you have obtained 180 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '190 Points',
                    'description' => 'Unlocks after you have obtained 190 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => '200 Points',
                    'description' => 'Unlocks after you have obtained 200 points in a single game.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Murder Snake',
                    'description' => 'Kill an other snake.',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Homicidal Viper',
                    'description' => 'Kill 25 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Killer Python',
                    'description' => 'Kill 100 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Slayer of Constrictors',
                    'description' => 'Kill 500 other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Murderous Anaconda',
                    'description' => 'Kill 1k other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Underground Mamba',
                    'description' => 'Kill 5k other snakes',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Getting Snaky',
                    'description' => 'Reach a length of 1k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Lengthy Reptile',
                    'description' => 'Reach a length of 10k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Elongated Cobra',
                    'description' => 'Reach a length of 100k',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Infinite Invertebrate',
                    'description' => 'Reach a length of 1m',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Hungry Snakelet',
                    'description' => 'Eat 1k pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Gluttonous Adder',
                    'description' => 'Eat 50k pellets',
                ],
                [
                    'id' => Str::uuid(),
                    'created_at' => now(),
                    'updated_at' => now(),
                    'name' => 'Voracious Habu',
                    'description' => 'Eat 1m pellets',
                ],
            ])->merge(
                Achievement::factory()
                    ->count(300)
                    ->make()
                    ->toArray(),
            ),
        ]);
    }
}
