<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Str;

class DemoUsersSeeder extends Seeder
{
    public function run()
    {
        User::insert($this->users()->toArray());
    }

    protected function users()
    {
        return collect([
            [
                'id' => Str::uuid(),
                'name' => 'Danyel',
                'last_name' => 'Alkeddah',
                'email' => 'danyel@alternativa.dev',
                'image' => null,
                'username' => 'danyelkeddah',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Amer',
                'last_name' => 'KJ',
                'email' => 'amer.kj@alternativa.dev',
                'image' => null,
                'username' => 'amerkj',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Tarik',
                'last_name' => 'Al Hafez',
                'email' => 'tarik@alternativa.dev',
                'image' => null,
                'username' => 'tarik',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Yaman',
                'last_name' => 'Jamal',
                'email' => 'yaman.jamal@alternativa.dev',
                'image' => null,
                'username' => 'yamanjamal',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Serhat',
                'last_name' => 'Tanrikut',
                'email' => 'serhat@wodo.io',
                'image' => null,
                'username' => 'serhattanrikut',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Bekir',
                'last_name' => 'Dag',
                'email' => 'bekir@wodo.io',
                'image' => null,
                'username' => 'bekirdag',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Furkan',
                'last_name' => 'Abay',
                'email' => 'furkan@wodo.io',
                'image' => null,
                'username' => 'thfurkanabay',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Kerem',
                'last_name' => 'Inci',
                'email' => 'kerem@wodo.io',
                'image' => null,
                'username' => 'kereminci',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Murat',
                'last_name' => 'Inci',
                'email' => 'murat@wodo.io',
                'image' => null,
                'username' => 'muratdemirci',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Gulsah',
                'last_name' => 'Smith',
                'email' => 'gulsah@wodo.io',
                'image' => null,
                'username' => 'gulsah',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Hasan',
                'last_name' => 'Smith',
                'email' => 'hasan@wodo.io',
                'image' => null,
                'username' => 'hasan',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Burak',
                'last_name' => 'Bolukbas',
                'email' => 'burakbolukbas@wodo.io',
                'image' => null,
                'username' => 'burakbolukbas',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Burak',
                'last_name' => 'Smith',
                'email' => 'burak@wodo.io',
                'image' => null,
                'username' => 'burak',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Sevban',
                'last_name' => 'Smith',
                'email' => 'sevban@wodo.io',
                'image' => null,
                'username' => 'sevban',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Pam',
                'last_name' => 'Smith',
                'email' => 'pam@wodo.io',
                'image' => null,
                'username' => 'pam',
                'email_verified_at' => now(),
                'password' => '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
